version: '3.8'

services:
  mac-authserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: mac-authserver:v0.0.2
    container_name: mac-authserver
    hostname: mac-authserver
    volumes:
      - ./config.json:/app/config.json:ro
      - ./mac-authserver.keytab:/etc/mac-authserver.keytab:ro
      - ./krb5.conf:/etc/krb5.conf:ro
    environment:
      - CONFIG_PATH=/app/config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - proxy-network

  envoy:
    image: envoyproxy/envoy:v1.36.4
    container_name: envoy-proxy
    hostname: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "80:80"
      # - "9901:9901"
    command: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy-network

  # Example of how metrics can be pulled and served
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - proxy-network

  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=AstraLinux123!
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://host-1.ald.company.lan/
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge

volumes:
  prometheus-data:
