[libdefaults]
    default_realm = ALD.COMPANY.LAN
    dns_lookup_realm = true
    dns_lookup_kdc = true
    forwardable = true

[realms]
    ALD.COMPANY.LAN = {
        kdc = dc-1.ald.company.lan
        admin_server = dc-1.ald.company.lan
        master_kdc = dc-1.ald.company.lan
        default_domain = ald.company.lan
    }

[domain_realm]
    .ald.company.lan = ALD.COMPANY.LAN
    ald.company.lan = ALD.COMPANY.LAN
